# Generated by Django 4.1.7 on 2023-03-16 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medecine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(max_length=255, verbose_name="Batch Number"),
                ),
                (
                    "medecine_name",
                    models.CharField(max_length=255, verbose_name="Medecine Name"),
                ),
                ("specification", models.TextField(verbose_name="Specification")),
                (
                    "measurement",
                    models.CharField(max_length=50, verbose_name="Measurement"),
                ),
                ("remarks", models.TextField(verbose_name="Remarks")),
                ("price", models.FloatField(verbose_name="Price")),
                (
                    "retail_price",
                    models.FloatField(max_length=255, verbose_name="Retail Price"),
                ),
                (
                    "quantity_on_hand",
                    models.IntegerField(verbose_name="Quantity on Hand"),
                ),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=255, verbose_name="First Name"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=255, verbose_name="Last Name"),
                ),
                ("about", models.TextField(verbose_name="About Me")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("SELECT GENDER", ""),
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="SELECT GENDER",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "employ_id",
                    models.CharField(max_length=100, verbose_name="Employee ID"),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Location Address"),
                ),
                (
                    "registerd_date",
                    models.DateField(auto_now_add=True, verbose_name="Registered Date"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=255, verbose_name="First Name"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=255, verbose_name="Last Name"),
                ),
                ("about", models.TextField(verbose_name="About Me")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("SELECT GENDER", ""),
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="SELECT GENDER",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "station_address",
                    models.CharField(max_length=255, verbose_name="Location Address"),
                ),
                (
                    "registerd_date",
                    models.DateField(auto_now_add=True, verbose_name="Registered Date"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_no",
                    models.CharField(max_length=255, verbose_name="Transaction No"),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                ("price", models.FloatField(verbose_name="Price")),
                ("amount", models.FloatField(verbose_name="Amount")),
                (
                    "reference_no",
                    models.CharField(max_length=255, verbose_name="Reference No"),
                ),
                (
                    "date_processed",
                    models.DateField(auto_now_add=True, verbose_name="Date Processed"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacy.pharmacist",
                        verbose_name="Pharmacist",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.medecine",
                        verbose_name="Medecine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceivedMedecine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(max_length=255, verbose_name="Reference No"),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                ("price", models.FloatField(verbose_name="Price")),
                ("amount", models.FloatField(verbose_name="Amount")),
                ("status", models.BooleanField(verbose_name="Request Status")),
                (
                    "date_processed",
                    models.DateField(auto_now_add=True, verbose_name="Date Processed"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacy.pharmacist",
                        verbose_name="Pharmacist",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.medecine",
                        verbose_name="Medecine",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PharmacyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_no",
                    models.CharField(max_length=255, verbose_name="Request No"),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity on Hand")),
                (
                    "status",
                    models.BooleanField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        verbose_name="Request Status",
                    ),
                ),
                (
                    "date_processed",
                    models.DateField(auto_now_add=True, verbose_name="Date Processed"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacy.pharmacist",
                        verbose_name="Pharmacist",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.medecine",
                        verbose_name="Medecine",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedecineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(max_length=255, verbose_name="Medecine Type"),
                ),
                (
                    "registerd_date",
                    models.DateField(auto_now_add=True, verbose_name="Registered Date"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacy.pharmacist",
                        verbose_name="Pharmacist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedecineCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=255, verbose_name="Medecine Category"),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Created Date"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacy.pharmacist",
                        verbose_name="Pharmacist",
                    ),
                ),
                (
                    "medecine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.medecinetype",
                        verbose_name="Medecine Type",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="medecine",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pharmacy.medecinecategory",
                verbose_name="Medecine Category",
            ),
        ),
        migrations.AddField(
            model_name="medecine",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pharmacy.pharmacist",
                verbose_name="Pharmacist",
            ),
        ),
    ]
